phase: f04_targets
variant: v4_0010
parent: v3_0002
parameters:
  parent_variant: v3_0002
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 340
  prediction_name: pvpcs_active_power_high_80_fine_4
  target_operator: OR
  target_event_types:
  - PVPCS_Active_Power_0_20-to-80_100
  - PVPCS_Active_Power_20_40-to-80_100
  - PVPCS_Active_Power_40_60-to-80_100
  - PVPCS_Active_Power_60_80-to-80_100
parent_hashes:
  v3_0002: 467a38cb11989bf6426d3982a5a04f7fd97cef6f2f144f40924be40659197182
