phase: f04_targets
variant: v4_0014
parent: v3_0002
parameters:
  parent_variant: v3_0002
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 340
  prediction_name: mg_lv_msb_ac_voltage_high_80_fine_4
  target_operator: OR
  target_event_types:
  - MG-LV-MSB_AC_Voltage_0_20-to-80_100
  - MG-LV-MSB_AC_Voltage_Set_Response_0_20-to-80_100
  - MG-LV-MSB_AC_Voltage_20_40-to-80_100
  - MG-LV-MSB_AC_Voltage_Set_Response_20_40-to-80_100
  - MG-LV-MSB_AC_Voltage_40_60-to-80_100
  - MG-LV-MSB_AC_Voltage_Set_Response_40_60-to-80_100
  - MG-LV-MSB_AC_Voltage_60_80-to-80_100
  - MG-LV-MSB_AC_Voltage_Set_Response_60_80-to-80_100
parent_hashes:
  v3_0002: 3b3bf7ea313b9ccaa473f8867d7574567243aa4b822771cb0c3b86e1ad0ba289
