phase: f04_targets
variant: v4_0012
parent: v3_0002
parameters:
  parent_variant: v3_0002
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 340
  prediction_name: pvpcs_active_power_low_20_fine_4
  target_operator: OR
  target_event_types:
  - PVPCS_Active_Power_20_40-to-0_20
  - PVPCS_Active_Power_Set_Response_20_40-to-0_20
  - PVPCS_Active_Power_40_60-to-0_20
  - PVPCS_Active_Power_Set_Response_40_60-to-0_20
  - PVPCS_Active_Power_60_80-to-0_20
  - PVPCS_Active_Power_Set_Response_60_80-to-0_20
parent_hashes:
  v3_0002: 3b3bf7ea313b9ccaa473f8867d7574567243aa4b822771cb0c3b86e1ad0ba289
